services: 
  postgres:
    image: bitnami/postgresql:latest
    container_name: pg
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh:ro
    ports: 
      - "5432:5432"
    networks:
      - analytics
  
  redash:
    image: redash/redash:25.8.0
    container_name: rsh
    environment:
      REDASH_DATABASE_URL: postgresql://wow_user:${PASS}@postgres:5432/wow_stats
      REDASH_REDIS_URL: redis://redis:6379
      REDASH_COOKIE_SECRET: very_secret
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    networks:
      - analytics
  
  redis:
    image: redis:8.4.0
    container_name: redis
    networks:
      - analytics
    
  generator:
    build:
      context: ./src/generator
    container_name: gen
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${USER}
      DB_PASS: ${PASS}
      GENERATION_INTERVAL: 1
    networks:
      - analytics

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadm
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - analytics

volumes:
  postgres_data:

networks:
  analytics:
    driver: bridge