[project]
name = "i-am-tired"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "psycopg2>=2.9.11",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "uv>=0.9.18",
]
